### ISSUE TITLE
No notification sent to Slack from DokuWiki

### ISSUE THREAD

**Issue by shashank-ssriva** [mallchin/dokuwiki-slack-notifier#6]
I am not receiving any notifications from DokuWiki in Slack using this plugin.

**Comment by yoyoys** [comment]
i have the same issue too

**Comment by caotu** [comment]
Please update your plugin.

**Comment by adanvdo** [comment]
The problem I ran into was that I had specified compound namespaces in the configuration (wiki:second:third) and the plugin was always only checking the first namespace to see if it was added as a valid namespace.

The _valid_namespace function in action.php is checking for `in_array($thisNamespaceArr[0], $validNamespacesArr);` which was returning false because i did not have "wiki" in my list of valid namespaces. I only had "wiki:second:third" and the plugin would reject it immediately.

I changed it to check instead for `in_array(implode(':', $thisNamespaceArr), $validNamespacesArr);`

This has solved the problem for me.

**Comment by caotu** [comment]
Thank for adanvdo. 

but this docs not work for me.  Hope author can update plugin soon.

**Comment by dbrieck** [comment]
This plugin seems to require the php curl module. I'm guessing that's why you're having issues with it not working.

**Comment by glensc** [comment]
@adanvdo if this is still an issue create new issue at:
- https://github.com/glensc/dokuwiki-plugin-slacknotifier/issues

@dbrieck: curl dependency is removed:
- https://github.com/glensc/dokuwiki-plugin-slacknotifier/pull/2

**Comment by mallchin** [comment]
Closed in favour of https://github.com/glensc/dokuwiki-plugin-slacknotifier.
